name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Generate the pacman-contribution-graph.svg using the correct action
      - name: Generate pacman-contribution-graph.svg
        uses: iceddev/pacman-contribution-graph@v1
        with:
          github_user_name: Rhuan-Zucarelli

      # Push the generated pacman-contribution-graph.svg to the output branch
      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
